# Use an official Maven runtime as a parent image
FROM maven:3.8.4-openjdk-17-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the Maven project files into the container
COPY . .

# Build the Maven project
RUN mvn clean install -Dmaven.test.skip=true

# Expose the port that your Spring Boot app is listening on (change this to your app's port)
EXPOSE 8080

# Define the command to run your Spring Boot application
CMD ["java", "-jar", "target/service-1.0.jar"]