version: '3'
services:
  secret:
    container_name: secret-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - mynetwork
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: secretkeeper

  db:
    image: mysql:latest
    container_name: mysql-db
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secretkeeper
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  mynetwork:

volumes:
  mysql-data:
