---
- name: Deploy Secret Service
  hosts: secret
  vars:
    ansible_shell: "/bin/bash"
  become: true
  become_user: ubuntu
  gather_facts: false

  tasks:
    - name: Docker login
      docker_login:
        username: "{{ lookup('env', 'DOCKER_HUB_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_HUB_PASSWORD') }}"
      ignore_errors: false

#    - name: Debug Docker login details
#      debug:
#        msg: "Docker login details - Username: {{ lookup('env', 'DOCKER_HUB_USERNAME') }}, {{ DOCKER_HUB_USERNAME }}, Password: {{ lookup('env', 'DOCKER_HUB_PASSWORD') }}, User: {{ lookup('env', 'USER') }}"

    - name: Pull Docker images
      command: "docker compose pull"
      args:
        chdir: "/home/ubuntu/secret-project"

    - name: Start Docker Compose services
      command: "docker compose up -d"
      args:
        chdir: "/home/ubuntu/secret-project"
