---
- name: Deploy Secret Service
  hosts: secret
  gather_facts: false

  tasks:
    - name: Docker login
      docker_login:
        username: "avi.energetics@gmail.com"
        password: "dckr_pat_msvUE1p3oUDAscs6UpPGcPDUWqg"
      ignore_errors: false

#    - name: Debug Docker login details
#      debug:
#        msg: "Docker login details - Username: {{ lookup('env', 'DOCKER_HUB_USERNAME') }}, {{ DOCKER_HUB_USERNAME }}, Password: {{ lookup('env', 'DOCKER_HUB_PASSWORD') }}, User: {{ lookup('env', 'USER') }}"

    - name: Pull Docker images
      command: "docker compose pull"
      args:
        chdir: "/home/ubuntu/secret-project"

    - name: Start Docker Compose services
      command: "docker compose up -d"
      args:
        chdir: "/home/ubuntu/secret-project"
