---
- name: Deploy Secret Service
  hosts: secret
  gather_facts: true

  tasks:
#    - name: Add host key to known_hosts
#      command: ssh-keyscan 44.203.224.77 >> ~/.ssh/known_hosts

    - name: Set Docker Hub credentials from environment
      set_fact:
        docker_hub_username: "{{ lookup('env', 'DOCKER_HUB_USERNAME') }}"
        docker_hub_password: "{{ lookup('env', 'DOCKER_HUB_PASSWORD') }}"

    - name: Print environment variables
      command: "env"
      register: out

    - debug: var=out.stdout_lines

    - name: Check if Docker Hub credentials are set
      fail:
        msg: "DOCKER_HUB_USERNAME and DOCKER_HUB_PASSWORD environment variables are required."
      when: docker_hub_username is not defined or docker_hub_password is not defined

    - name: Docker login
      docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"
      ignore_errors: false

    - name: Debug Docker login details
      debug:
        msg: "Docker login details - Username: {{ docker_hub_username }},{{ lookup('env', 'DOCKER_HUB_USERNAME') }}, Password: {{ docker_hub_password }},{{ lookup('env', 'DOCKER_HUB_PASSWORD') }}, User: {{ lookup('env', 'USER') }}"

    - name: Pull Docker images
      command: "docker compose pull"
      args:
        chdir: "/home/ubuntu/secret-project"

    - name: Start Docker Compose services
      command: "docker compose up -d"
      args:
        chdir: "/home/ubuntu/secret-project"
